# Generated by Django 5.1.4 on 2025-05-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrostore', '0002_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('sega', 'Sega'), ('nintendo', 'Nintendo'), ('atari', 'Atari'), ('playstation', 'PlayStation'), ('dreamcast', 'Dreamcast')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
